export default {
    first: require('../Images/pilatis3.png'),
    second: require('../Images/pilatis5-effect.png'),
    third: require('../Images/sports4eti.jpg'),
    fourth: require('../Images/pilatis4-effect.png'),
    fifth: require('../Images/etifitnesscubeedited.jpg'),
    sixth: require('../Images/darkpilates.jpg'),
    seventh: require('../Images/leftinsta.jpg'),
    eight: require('../Images/young-fitness-girl-running-up-the-stairs.jpg'),
    nine: require('../Images/two-women-doing-yoga.jpg'),
    ten: require('../Images/fitness-women-sports-gym.jpg'),
    fb: require('../Images/facebookicon.png'),
    fb1: require('../Images/fb.png'),
    etikidscube: require('../Images/etikidscube.jpg'),
    etikidsspiral1: require('../Images/etikidsspiral1.jpg'),
    etikidsspiral2: require('../Images/etikidsspiral2.jpg'),
    etikidsspiral3: require('../Images/etikidsspiral3.jpg'),
    etikidsedited: require('../Images/etikidsedited.jpg'),
    etifitnesscubeedited: require('../Images/etifitnesscubeedited.jpg'),
};
